/**
 * Named-entity resolution for VOKO XML.
 *
 * Articles declare `<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">` and use
 * ~565 named entities (&ccirc; &c_a; &FE; …) defined in voko-grundo's DTDs.
 * `data/entities.json` is the fully resolved map, generated by
 * `scripts/gen-entities.ts` from the vendor/voko-grundo submodule (not
 * committed; run `bun run fonto`). Substitution happens on the raw text before the XML
 * parser sees it; the five XML built-ins and numeric char refs are left for the
 * parser.
 */
import entitiesJson from "../data/entities.json";

export const ENTITIES: Readonly<Record<string, string>> = entitiesJson;

const BUILTIN = new Set(["amp", "lt", "gt", "apos", "quot"]);
const ENTITY_RE = /&([A-Za-z_][\w.\-]*);/g;

export class UnknownEntityError extends Error {
  constructor(public readonly entity: string, public readonly file?: string) {
    super(`unknown entity &${entity};${file ? ` in ${file}` : ""}`);
  }
}

/** Replace every non-builtin named entity with its Unicode value. Throws on unknown names. */
export function substituteEntities(text: string, file?: string): string {
  if (!text.includes("&")) return text;
  return text.replace(ENTITY_RE, (whole, name: string) => {
    if (BUILTIN.has(name)) return whole;
    const v = ENTITIES[name];
    if (v === undefined) throw new UnknownEntityError(name, file);
    return v;
  });
}

/** Unicode char → entity name, for the entity-encoding serializer mode. */
let reverse: Map<string, string> | null = null;
export function entityFor(char: string): string | undefined {
  if (!reverse) {
    reverse = new Map();
    for (const [name, value] of Object.entries(ENTITIES)) {
      // Only single-codepoint values are re-encodable; abbreviations like &FE;
      // ("Ekzercaro, §") are text macros and must stay expanded.
      if ([...value].length === 1 && !reverse.has(value)) reverse.set(value, name);
    }
  }
  return reverse.get(char);
}
